-- CreateTable
CREATE TABLE "Games" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "ReleaseDate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "highlight" BOOLEAN NOT NULL DEFAULT false,
    "id_Genre" INTEGER NOT NULL DEFAULT 0,
    "id_Editor" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "Games_id_Genre_fkey" FOREIGN KEY ("id_Genre") REFERENCES "Genres" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Games_id_Editor_fkey" FOREIGN KEY ("id_Editor") REFERENCES "Editors" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Genres" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "Editors" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "IsDeleted" BOOLEAN NOT NULL DEFAULT false
);
